### ISSUE TITLE
excuseme

### ISSUE THREAD

**Issue by Slava** [weblab-staff/shorten#1]
is the existing app not getting more love? T_T
https://github.mit.edu/mit6148/shortener

**Comment by cory2067** [comment]
meteor wanted to use 500gb of memory so i gave up

**Comment by Slava** [comment]
what

**Comment by asipser** [comment]
we tried deploying it on digital ocean on the smallest possible droplet and it oom'd every time :cry: if there is a lightweight way to run the meteor shortener would love to know

**Comment by Slava** [comment]
If you run it in prod mode as described in tech bible and not in
development mode, it won't need RAM at all.
